indent_type = "Spaces"
indent_width = 2
column_width = 120
collapse_simple_statement = "Always"
syntax = "Lua51"
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
line_endings = "Unix"
space_after_function_names = "Never"
block_newline_gaps = "Never"
[sort_requires]
enabled = true
